### ISSUE TITLE
adding (?) iterable cadwork.point_3d over x, y, z components?

### ISSUE THREAD

**Issue by fbpyr** [cwapi3d/cwapi3dpython#11]
I was wondering if cwAPI3d could make the cadwork.point_3d iterable over x, y, z?

This would help to loop over x, y, z like this:

```python
for component in cadwork.point_3d(1.0, 2.0, 3.0):
    print(component)
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#TypeError: 'cadwork.point_3d' object is not iterable
#
#'cadwork.point_3d' object is not iterable
```

and also make it possible to conveniently unpack it:

```python
x, y, z = cadwork.point_3d(1.0, 2.0, 3.0)
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#TypeError: cannot unpack non-iterable cadwork.point_3d object
#
#cannot unpack non-iterable cadwork.point_3d object
```

What are your thoughts? 🤔

**Comment by Brunner246** [comment]
This will be implemented in cadwork **version 29**. 
As an interim solution, the class point_3d can be inherited. 



```python
from cadwork import point_3d
import math
class Vector_3d(point_3d):
    def __init__(self, x:float, y:float, z:float) -> None:
        super().__init__(x,y,z)
    def __getitem__(self, i):
        if i == 0:
            return self.x
        elif i == 1:
            return self.y
        elif i == 2:
            return self.z
        else:
            raise IndexError('Index out of range')
    def __setitem__(self, i, val):
        if i == 0:
            self.x = val
        elif i == 1:
            self.y = val
        elif i == 2:
            self.z = val
        else:
            raise IndexError('Index out of range')
  ..............
  .........
```

**Comment by fbpyr** [comment]
@Brunner246  Thank you! 
For now I went over `point_3d` via getattr: 
`[getattr(cw.point_3d(1.0,2.0,0.0), d) for d in ("x", "y", "z")]`
but if it will be built in, that will be way nicer! 🙂

**Comment by Brunner246** [comment]
@fbpyr 

In version 29 of cadwork, the point_3d is now iterable and unpackable.

```python
x, y, z = cadwork.point_3d(1200,1200,2500)

for p in cadwork.point_3d(1200,1200,2500):
    print(p)
```
