### ISSUE TITLE
any changes made to get_element_facets(element_id) ?

### ISSUE THREAD

**Issue by Brunner246** [cwapi3d/cwapi3dpython#204]
### Discussed in https://github.com/cwapi3d/cwapi3dpython/discussions/203

<div type='discussions-op-text'>

<sup>Originally posted by **roehligas** August  7, 2024</sup>
Hi,

one of our scripts throws an error that wasn't there before.

```
Traceback (most recent call last):
  File "K:\02 KONSTRUKSJON\04 CADWORK\Cadwork_lib\userprofil_30\3d\API.x64\GenerateDoorBeams\GenerateDoorBeams.py", line 73, in <module>
    ess.main()
  File "//dc-1/Felles\02 KONSTRUKSJON/04 CADWORK/Cadwork_lib/USERPROFIL_30/3d/API.x64/GenerateDoorBeams\GenerateDoorBeams_lib.py", line 315, in main
    create_doorbeams([ae])
  File "//dc-1/Felles\02 KONSTRUKSJON/04 CADWORK/Cadwork_lib/USERPROFIL_30/3d/API.x64/GenerateDoorBeams\GenerateDoorBeams_lib.py", line 266, in create_doorbeams
    for i in range(len(facet)-1):
TypeError: object of type 'cadwork.vertex_list' has no len()
```

Have changes been made to this function? Before a python list containing a list of point3d objects was returned, now it is it's own class.

I need some documentation on this new class so that i can update our scripts</div>

**Comment by Brunner246** [comment]
@roehligas changes/fixes will be available within the next cadwork 3d live-update

```python
import element_controller as ec
import cadwork
import geometry_controller as gc

ec.get_active_identifiable_element_ids()
[62748055]
facets = gc.get_element_facets(62748055)
len(facets)
6
facets[6]
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    facets[6]
IndexError: index out of range!
```
